---
title: "Literature review"
author: "Daniel Dennis"
date: "09/06/2021"
output: pdf_document
bibliography: /Users/danieldennis/dissertation/references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Modelling the demand for gas is vital to help meet the varying needs of the smallest residential user to the largest industrial user, and everything in between. Residential and commercial users require gas most notably for heating and cooking, while industrial users require gas for larger operations, including manufacturing processes and as a component in producing goods, @king. There are many studies modelling the demand for gas for residential and commercial consumers, or for an aggregate of all three consumers, particularly providing short- to medium-term forecasts. However, since the research in this paper is focused on modelling industrial demand for gas, this will be the main focus of this review.

A common feature, particularly in studies focused on residential and commercial customers, is a model based on weather- and calendar-related factors. The weather-related factors largely influence gas consumption due to users changing their heating demands, @timmer, while calendar-related factors generally reference the differences in gas consumption on weekdays, weekends, and public holidays due to changes in working patterns, @franco. Other factors are noted for their possible impact on demand for gas, such as oil prices, GDP, and population growth. These factors are usually referenced in some scope, with some papers disregarding them after concluding their impact on short and medium-term forecasting horizons is negligible (e.g., @sanchezubeda), while other papers evidence their importance and integrate such factors into their model (e.g., @zhu).

Early work on the subject by @lyness, describes how the British Gas Corporation uses a Box-Jenkins model to produce short- and medium-term forecasts, with a view of a top-down or bottom-up approach for long-term forecasting. The bottom-up approach could be to take assumptions based on the number of gas appliances in the market and their corresponding gas usage, allowing a calculation for total demand. The top-down approach would be looking at the total demand for energy per sector, then breaking this down to the level for gas. Lyness’s paper recognised the underlying patterns of demand; where daily consumption follows a “diurnal swing” (the temperature pattern from the daily high to the daily low), a weekly cycle where weekends and weekdays exhibit different consumption patterns, and annual consumption following a roughly sinusoidal curve linked to seasonal temperature variations. For a detailed overview of the topic, both @vitullo, and @soldo, discuss a range of statistical models and the factors these are based upon, with the latter also providing insight on computer science-driven models.

@sanchezubeda, present a novel approach combining quantitative and qualitative forecasts for industrial users in Spain. This uses a model equation which features trend, seasonal, and transitory components, and encodes calendar information categorized by days of the week, weekends, and holidays. @huntington, presents analysis which adopts a general autoregressive distributed lag relationship to model future trends of industrial natural gas consumption in the United States. The variables included in the model are current and lagged values of natural gas consumption and a set of independent explanatory variables, comprising of industrial natural gas price, distillate fuel oil price, structural output, heating degree-days[^1] and capacity utilisation. @zhu, similarly include several socioeconomic variables to their model. GDP, total population and urbanization rate were used as the input variables as they constructed a radial basis function neural network quantile regression model. The results of this were combined with those of a Bayesian vector autoregression model, providing a combinational forecast for China’s gas consumption. @wang, use a multiverse optimiser algorithm to optimise the parameters of the Nash non-linear grey Bernoulli model, proposing a hybrid of the models to predict natural gas consumption in 30 regions across China. @laib, model demand in Algeria using a Gaussian process regression based on time series data, using lagged consumption observations, three temperature readings and clustering with several combinations of seasonal labels. @heaps, examine the demand for gas in the same two regions featured in this paper, however their work investigates the effect of public holidays on residential daily demand for gas. A four-state, non-homogeneous hidden Markov model is used, featuring a so-called proximity effect to model the days leading up to and away from public holidays.

The existing body of literature illustrates that modelling and forecasting gas demand is successful through a wide range of techniques. Studies contain many combinations of different variables as the backbone of the model, each providing a compelling case for their inclusion. A good deal of the studies that focus on industrial gas consumption use data from rapidly developing countries, which likely follow a different pattern of demand to the North and North East of England. A common feature in the existing literature is to group residential, commercial, and industrial demand together, leaving a gap for purely industrial gas demand modelling. The studies performed in this paper will provide unique research by building a model for industrial gas demand in the aforementioned regions of England.

[^1]: “Heating degree days are a measure of how much (in degrees), and for how long (in days), outside air temperature was higher than a specific base temperature” - https://www.degreedays.net/

\newpage
### References